image: registry.gitlab.com/picodata/dockers/stroppy_builder:v2

stages:
- build
- docker

build:
  stage: build
  script:
    - cd benchmark
    # - git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    - go env -w GO111MODULE=auto
    - go mod tidy
    # - go get gitlab.com/picodata/benchmark/stroppy/pkg/database/config
    - go build -o bin/stroppy ./cmd/stroppy
  artifacts:
    paths:
    - benchmark/bin/

lint:
  stage: build
  variables:
    # gitlab internally fetches only current HEAD in detached state
    # add master refspec as fetch arg to make 'git diff master' possible
    GIT_FETCH_EXTRA_FLAGS: refs/heads/master:refs/remotes/origin/master
  image: registry.gitlab.com/picodata/dockers/stroppy_linter:v2
  script:
    - cd benchmark
    - go get gitlab.com/picodata/benchmark/stroppy/pkg/database/config
    - golangci-lint run --new-from-rev=$(git merge-base origin/master HEAD) --timeout 1m30s

docker:
  image: docker:dind
  stage: docker
  tags: 
    - docker
  services:
  - docker:dind
  only:
    - master
    - /^staging-.*$/
    - /^hotfix-.*$/
    - check-ci
  artifacts:
    paths:
      - benchmark/docker-tag.txt
    expire_in: 1 month
  before_script:
    - cd benchmark
  script:
    - CD_DOCKER_TAG=`date +'%Y-%m-%d'`_$CI_COMMIT_SHA
    - echo $CD_DOCKER_TAG > docker-tag.txt
    - CD_DOCKER_IMAGE=$CI_REGISTRY_IMAGE:$CD_DOCKER_TAG
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - DOCKER_LATEST=$CI_REGISTRY_IMAGE:latest
    - docker build -t $CD_DOCKER_IMAGE -t $DOCKER_LATEST --build-arg COMMIT_HASH=$CI_COMMIT_SHA .
    - docker push $CD_DOCKER_IMAGE
    - docker push $DOCKER_LATEST
