apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-init
  labels:
<<<<<<< HEAD
    worker-type: dbms-worker
=======
    app: cockroachdb
>>>>>>> fix: в папке на кластер из пяти машин обновил файлы разворачивания (они устарели),
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        image: cockroachdb/cockroach:v21.2.0
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "init"
          - "--insecure"
          - "--host=cockroachdb-0.cockroachdb"
      restartPolicy: OnFailure
