apiVersion: v1
kind: Pod
metadata:
  name: stroppy-client
  namespace: default
spec:
  containers:
  - name: stroppy-client
    image: registry.gitlab.com/picodata/openway/stroppy:latest
  imagePullSecrets:
  - name: stroppy-secret

